# Generated by Django 4.1 on 2023-11-01 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titler', models.CharField(max_length=250, verbose_name='услуга тура:')),
                ('titler_ru', models.CharField(max_length=250, null=True, verbose_name='услуга тура:')),
                ('titler_en', models.CharField(max_length=250, null=True, verbose_name='услуга тура:')),
            ],
            options={
                'verbose_name': 'услуга тура',
                'verbose_name_plural': 'услуги туров',
            },
        ),
        migrations.CreateModel(
            name='TourPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tur', models.CharField(max_length=250, verbose_name='Название тура')),
                ('name_tur_ru', models.CharField(max_length=250, null=True, verbose_name='Название тура')),
                ('name_tur_en', models.CharField(max_length=250, null=True, verbose_name='Название тура')),
                ('day_tur', models.CharField(max_length=250, verbose_name='День')),
                ('day_tur_ru', models.CharField(max_length=250, null=True, verbose_name='День')),
                ('day_tur_en', models.CharField(max_length=250, null=True, verbose_name='День')),
                ('comment_turs', models.TextField(verbose_name='Описание')),
                ('comment_turs_ru', models.TextField(null=True, verbose_name='Описание')),
                ('comment_turs_en', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'План тура',
                'verbose_name_plural': 'Планы тура',
            },
        ),
        migrations.CreateModel(
            name='Turs_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_turs', models.CharField(choices=[('Пляжный', 'Пляжный'), ('Национальный', 'Национальный'), ('Шоппинг', 'Шоппинг'), ('Экскурсии', 'Экскурсии'), ('Экстремальный', 'Экстремальный'), ('Горные лыжи', 'Горные лыжи')], max_length=100)),
                ('type_turs_ru', models.CharField(choices=[('Пляжный', 'Пляжный'), ('Национальный', 'Национальный'), ('Шоппинг', 'Шоппинг'), ('Экскурсии', 'Экскурсии'), ('Экстремальный', 'Экстремальный'), ('Горные лыжи', 'Горные лыжи')], max_length=100, null=True)),
                ('type_turs_en', models.CharField(choices=[('Пляжный', 'Пляжный'), ('Национальный', 'Национальный'), ('Шоппинг', 'Шоппинг'), ('Экскурсии', 'Экскурсии'), ('Экстремальный', 'Экстремальный'), ('Горные лыжи', 'Горные лыжи')], max_length=100, null=True)),
                ('premium_comment', models.CharField(max_length=200, verbose_name='Описание уникального тура')),
                ('premium_comment_ru', models.CharField(max_length=200, null=True, verbose_name='Описание уникального тура')),
                ('premium_comment_en', models.CharField(max_length=200, null=True, verbose_name='Описание уникального тура')),
                ('adout_comment', models.CharField(max_length=200, verbose_name='Примечание к туру')),
                ('adout_comment_ru', models.CharField(max_length=200, null=True, verbose_name='Примечание к туру')),
                ('adout_comment_en', models.CharField(max_length=200, null=True, verbose_name='Примечание к туру')),
                ('premium', models.BooleanField(verbose_name='уникальный тур')),
                ('view', models.CharField(max_length=100, verbose_name='Вид тура')),
                ('view_ru', models.CharField(max_length=100, null=True, verbose_name='Вид тура')),
                ('view_en', models.CharField(max_length=100, null=True, verbose_name='Вид тура')),
                ('img_tur', models.ImageField(upload_to='media/')),
                ('name_tur', models.CharField(max_length=250, verbose_name='Название тура')),
                ('name_tur_ru', models.CharField(max_length=250, null=True, verbose_name='Название тура')),
                ('name_tur_en', models.CharField(max_length=250, null=True, verbose_name='Название тура')),
                ('season', models.CharField(max_length=250, verbose_name='Сезон')),
                ('season_ru', models.CharField(max_length=250, null=True, verbose_name='Сезон')),
                ('season_en', models.CharField(max_length=250, null=True, verbose_name='Сезон')),
                ('how_many_days', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Сколько дней')),
                ('how_many_nights', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Сколько ночей')),
                ('create_day', models.DateField(default=datetime.date.today, verbose_name='день создания тура')),
                ('duration_tur', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='длительность тура')),
                ('price', models.CharField(max_length=250, verbose_name='цена тура')),
                ('arrival_day', models.DateField(verbose_name='прилёт')),
                ('departure_day', models.DateField(verbose_name='вылет')),
                ('comment_turs', models.TextField(verbose_name='Описание тура')),
                ('comment_turs_ru', models.TextField(null=True, verbose_name='Описание тура')),
                ('comment_turs_en', models.TextField(null=True, verbose_name='Описание тура')),
                ('hotel_name', models.CharField(max_length=255, verbose_name='название отеля')),
                ('hotel_name_ru', models.CharField(max_length=255, null=True, verbose_name='название отеля')),
                ('hotel_name_en', models.CharField(max_length=255, null=True, verbose_name='название отеля')),
                ('hotel_eat', models.CharField(max_length=255, verbose_name='Питание')),
                ('hotel_eat_ru', models.CharField(max_length=255, null=True, verbose_name='Питание')),
                ('hotel_eat_en', models.CharField(max_length=255, null=True, verbose_name='Питание')),
                ('hotel_number', models.CharField(max_length=255, verbose_name='Номер отеля')),
                ('hotel_number_ru', models.CharField(max_length=255, null=True, verbose_name='Номер отеля')),
                ('hotel_number_en', models.CharField(max_length=255, null=True, verbose_name='Номер отеля')),
                ('arrival_city', models.CharField(max_length=255, verbose_name='c какого города вылет')),
                ('arrival_city_ru', models.CharField(max_length=255, null=True, verbose_name='c какого города вылет')),
                ('arrival_city_en', models.CharField(max_length=255, null=True, verbose_name='c какого города вылет')),
                ('departure_city', models.CharField(max_length=255, verbose_name='в какой город прилёт')),
                ('departure_city_ru', models.CharField(max_length=255, null=True, verbose_name='в какой город прилёт')),
                ('departure_city_en', models.CharField(max_length=255, null=True, verbose_name='в какой город прилёт')),
                ('NoServices', models.ManyToManyField(related_name='YesIncludedPrice', to='turs.includedprice', verbose_name='Не включено в стоимость:')),
                ('YesServices', models.ManyToManyField(related_name='NoIncludedPrice', to='turs.includedprice', verbose_name='Включено в стоимость:')),
                ('tru_io', models.ManyToManyField(blank=True, null=True, related_name='tru_io_pla', to='turs.tourplan', verbose_name='План тура')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
