# Generated by Django 4.1 on 2023-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turs_obj',
            name='NoServices_en',
            field=models.ManyToManyField(null=True, related_name='YesIncludedPrice', to='turs.includedprice', verbose_name='Не включено в стоимость:'),
        ),
        migrations.AddField(
            model_name='turs_obj',
            name='NoServices_ru',
            field=models.ManyToManyField(null=True, related_name='YesIncludedPrice', to='turs.includedprice', verbose_name='Не включено в стоимость:'),
        ),
        migrations.AddField(
            model_name='turs_obj',
            name='YesServices_en',
            field=models.ManyToManyField(null=True, related_name='NoIncludedPrice', to='turs.includedprice', verbose_name='Включено в стоимость:'),
        ),
        migrations.AddField(
            model_name='turs_obj',
            name='YesServices_ru',
            field=models.ManyToManyField(null=True, related_name='NoIncludedPrice', to='turs.includedprice', verbose_name='Включено в стоимость:'),
        ),
    ]
