# Generated by Django 4.1 on 2023-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turs', '0003_remove_turs_obj_noservices_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turs_obj',
            name='NoServices',
            field=models.ManyToManyField(blank=True, null=True, related_name='YesIncludedPrice', to='turs.includedprice', verbose_name='Не включено в стоимость:'),
        ),
        migrations.AlterField(
            model_name='turs_obj',
            name='YesServices',
            field=models.ManyToManyField(blank=True, null=True, related_name='NoIncludedPrice', to='turs.includedprice', verbose_name='Включено в стоимость:'),
        ),
    ]
